---
- hosts: 172.31.4.17
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: install server
    apt:
     name: apache2
     state: present

  - name: copy a file into ansible node side
    copy:
     src: mystaticfile.txt
     dest: /home/ubuntu/mystaticfile   
  