---
- hosts: 172.31.4.17
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: install server
    apt:
     name: apache2
     state: present

  - name: copy a file into ansible node side
    copy:
     src: mystaticfile.txt
     dest: /home/ubuntu/mystaticfile  
    notify: restartwebserver

  - name: copy index file into ansible node
    template:
      src: myindex.j2
      dest: /var/www/html/index.html  
    notify: restartwebserver     

  - name: download file from internate
    get_url:
      url:   https://get.jenkins.io/war-stable/2.375.1/jenkins.war 
      dest: /home/ubuntu/myjenkins.war
      force_basic_auth: yes

  handlers: 
  - name: restartwebserver
    service:
     name: apache2
     state: restarted
   
  