---
- hosts: myWebServers
  become: yes
  tasks: 
  - name: i want to install webserver on my ubuntu nodes
    apt:
     name: {{mywebpackubuntu}}
     state: present
    when: ansible_os_family== "Debian" 

  - name: i want to restart webserver on my ubuntu nodes
    service:
     name: {{mywebpackubuntu}}
     state: started
    when: ansible_os_family=="Debian" 

  - name: i want to install webserver on my RedHat nodes 
    yum: 
     name: {{mywebpackredhat}}
     state: present
    when: ansible_os_family=="RedHat" 

  - name: i want to restart webserver on my RedHat nodes
    service:
      name: {{mywebpackredhat}}
      state: started 
    when: ansible_os_family=="RedHat"   
     
