---
- hosts: all
  become: yes
  tasks: 
  - name: i want to install webserver on my ubuntu nodes
    apt:
     name: apache2
     state: present

  - name: i want to restart webserver on my ubuntu nodes
    service:
     name: apache2
     state: started
