---
# tasks file for mytomrole
- include_task: myuser.yml
- include_task: installjava.yml
- include_tasks: download.yml
- include_tasks: permissions.yml
- include_tasks: ConfigDashBoard.yml
- include_tasks: starttomcat.yml

